### ISSUE TITLE
UIJob.run: Device is disposed

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#276] opened 2022-08-19 11:47 UTC
```
!ENTRY org.eclipse.core.jobs 4 2 2022-08-19 13:43:41.250
!MESSAGE An internal error occurred during: "Animation start".
!STACK 0
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1254)
	at org.eclipse.swt.widgets.Display.asyncExec(Display.java:793)
	at org.eclipse.ui.progress.UIJob.run(UIJob.java:84)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

happened during org.eclipse.core.tests.internal.builders.BuilderTest

but there IS a disposed check?!

**Comment by laeubi** [comment] 2022-08-19 11:55
https://github.com/eclipse-platform/eclipse.platform.ui/blob/08c480b6f7aa3276bac6d1de4c262eade5ec73fb/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/progress/UIJob.java#L81-L84
In line 81 it is checked if the display is disposed, but if another thread dispose the display in line 84 it might be already be disposed.

**Comment by trancexpress** [comment] 2022-08-19 11:56
The code is not yet in the UI thread, I assume the display can be disposed in parallel (from the actual UI thread).

I'm not sure what the code is supposed to do in cases like this, since if the display is gone the entire UI is gone. But in theory the exception can be caught and treated like the disposed display case (return cancelled status). Maybe something else breaks after that point though.

What is the context here? Tests or just normal Eclipse use?

**Comment by jukzi** [comment] 2022-08-22 06:30
It happens only during the test. The interesting part is, that it can be 100% reproduced. That is not normal for race conditions.

**Comment by trancexpress** [comment] 2022-08-22 06:48
> It happens only during the test. The interesting part is, that it can be 100% reproduced. That is not normal for race conditions.

Does this help?

```
diff --git a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java b/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java
index 5591700564..8b478bd7ea 100644
--- a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java    
+++ b/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java    
@@ -81,6 +81,9 @@ public abstract class UIJob extends Job {
                if (asyncDisplay == null || asyncDisplay.isDisposed()) {
                        return Status.CANCEL_STATUS;
                }
+               if (!PlatformUI.isWorkbenchRunning()) {
+                       return Status.CANCEL_STATUS;
+               }
                asyncDisplay.asyncExec(() -> {
                        IStatus result = null;
                        Throwable throwable = null
```

If not, maybe this, but I'm less sure about it:

```
diff --git a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java b/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java
index 5591700564..3a6b489620 100644
--- a/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java    
+++ b/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/progress/UIJob.java    
@@ -81,6 +81,9 @@ public abstract class UIJob extends Job {
                if (asyncDisplay == null || asyncDisplay.isDisposed()) {
                        return Status.CANCEL_STATUS;
                }
+               if (!PlatformUI.isWorkbenchRunning() || PlatformUI.getWorkbench().isClosing()) {
+                       return Status.CANCEL_STATUS;
+               }
                asyncDisplay.asyncExec(() -> {
                        IStatus result = null;
                        Throwable throwable = null;
```

Likely some UI job does need to do something while the workbench is closing...

Or we just add a try-catch, check if the display is disposed in the catch and rethrow if not. WDYT?

**Comment by jukzi** [comment] 2022-08-22 07:04
none of the both helps.
The best way would be to have a clean Display.asyncExecIfStillRunning which just silently does not execute when disposed. i.e. only a single dispose check within the synchronized block of asyncExec.
i am still curious what synchronizes the Device.class for so long that it is reproducible.

**Comment by laeubi** [comment] 2022-08-22 07:09
If it is reproducible you should be able to find out what threads are involved, what jobs and why they interfere with each other..

**Comment by laeubi** [comment] 2022-08-22 07:22
By the way this is a great example on why these `dispose()` checks are silly. The calling code calls "isDisposed()" to do "nothing" while the implementing code also calls "isDisposed()" to throw an exception.... so one might argua that I better use try / catch her instead of checking disposed as it has no meaning anyways in the next line...

> The best way would be to have a clean Display.asyncExecIfStillRunning which just silently does not execute when disposed.

Being pedantic, this could be implemented with the current API (if we ignore the throws requirement) wich states:
> Causes the <code>run()</code> method of the runnable to
> be invoked by the user-interface thread at the next
> reasonable opportunity.

So given a Display is disposed, the "next reasonable opportunity" is simply never ;-)

**Comment by jukzi** [comment] 2022-08-22 07:44
another silly example:
```
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1254)
	at org.eclipse.swt.widgets.Display.getThread(Display.java:2587)
	at org.eclipse.ui.internal.progress.ProgressManager.monitorFor(ProgressManager.java:589)
	at org.eclipse.core.internal.jobs.JobManager.monitorFor(JobManager.java:1115)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:315)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:124)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2330)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by trancexpress** [comment] 2022-08-22 08:35
Are tests maybe missing waiting on jobs before shutting down the workbench?

**Comment by iloveeclipse** [comment] 2022-08-22 08:50
If I remember right,  there was code that created and disposed displays in some tests. So given that jobs run asynchronously to test code,  this is "expected".

**Closed as completed** 2022-09-06 11:14 UTC
