### ISSUE TITLE
Button toggle states "on" and "over" not obvious on default dark theme

### ISSUE THREAD

**Issue by OlivierJaquemet** [eclipse-platform/eclipse.platform.ui#648] opened 2023-03-20 10:21 UTC
Toggle state is described in the Eclipse UI Guidelines :
https://eclipse-platform.github.io/ui-best-practices/#toggled_states

When using the default light mode theme, the "on" and "over" states are quite obvious.

However, when using the default dark mode theme, the "on" and "over" states are almost indistinguishable from the "off" states, as seen in thefollowing captures which demonstrate the issue using the _Scroll Lock_ button of the _Console_ view.

Scroll lock - toggle state - OFF state : 
![scroll lock - toggle state - OFF](https://user-images.githubusercontent.com/618861/226311299-eb0e62aa-c24b-4ab4-94ea-f5ba5a8c58b4.png)

Scroll lock - toggle state - OVER state :
![scroll lock - toggle state - OVER](https://user-images.githubusercontent.com/618861/226311292-5fd6018c-61ca-4e61-aecf-9d220864e95d.png)

Scroll lock - toggle state - ON state :
![scroll lock - toggle state - ON](https://user-images.githubusercontent.com/618861/226311304-5784b208-4bb0-4be0-8d23-8a8c20135f4a.png)

Captured on Eclipse 2023-03 (4.27.0), on Windows 10.

**Comment by OlivierJaquemet** [comment] 2023-03-20 10:23
PS : 
- I could not change the behavior using the OS settings
- I would like the default Eclipse installation to be provide the best behavior and that's why I don't want to install plugin from the markeplace to fix this

**Comment by BeckerWdf** [comment] 2023-06-21 07:40
this is a duplicate of #340

**Closed as completed by BeckerWdf** 2023-06-21 07:40 UTC

**Comment by OlivierJaquemet** [comment] 2023-06-21 08:07
Thank you @BeckerWdf for the triage.
