### ISSUE TITLE
Tremendous vertical space introduced into UI elements

### ISSUE THREAD

**Issue by exabrial** [eclipse-platform/eclipse.platform.ui#1756] opened 2024-03-14 14:05 UTC
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Tested under this environment:
* OS & version: Mac OS Sonoma
* Eclipse IDE/Platform version (as shown in *Help > About*): 2024-3

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

A tremendous amount of vertical space has been introduced into the IDE for certain ui elements, wasting valuable vertical screen real estate. This bug affects multiple UI Elements, the most impactful is Project Explorer. Our projects have 28+ modules, which used to fit onto one screen, but no longer do. The Prefpane is also suffering from the issue and is easiest to capture, so I've included screenshots below. 

I can't find a preference or workaround at this time, so unfortunately the only recourse is to switch back to 2023-12 until this is resolved.

As always, thank you, happy to be an Eclipse user.

Vertical space bug in 2024-3:

![Screenshot 2024-03-14 at 8 35 20 AM](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1392297/0c7b4787-5561-4af0-857a-0b0a84f24162)

Previous version of Eclipse didn't contain bug 2023-12:

![Screenshot 2024-03-14 at 8 54 12 AM](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1392297/bace04fc-aa85-4f0d-8d54-0909d587f27e)

**Comment by BeckerWdf** [comment] 2024-03-14 14:07
Duplicate of #1674

**Closed as not planned by BeckerWdf** 2024-03-14 14:07 UTC
Labels: bug

**Comment by exabrial** [comment] 2024-03-14 14:09
Thank you! apologies for the duplicate

**Comment by BeckerWdf** [comment] 2024-03-14 14:13
> Thank you! apologies for the duplicate

Not an issue at all. Thanks for taking the time and reporting...
