### ISSUE TITLE
Find/Replace overlay: changes heigth on resize

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1995] opened 2024-06-25 08:56 UTC
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/e6542e0c-d2a5-4e96-a220-9c0b315d9f86) ![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/594e14c6-1164-4a66-977e-7b83fb87840b)

Fells like the buttons reserve to much space around them

**Comment by HeikoKlare** [comment] 2024-07-23 09:29
I cannot reproduce this anymore. I expected this to implicitly have been fixed via #2097, #2030 or some of the other layouting-related improvements.

**Closed as completed by HeikoKlare** 2024-07-23 09:29 UTC
Labels: bug
