### ISSUE TITLE
Dark mode hide ToolItem cheched state

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-platform/eclipse.platform.ui#530] opened 2023-01-27 14:46 UTC
In light mode :
![image](https://user-images.githubusercontent.com/3462260/215114254-fa67ff36-edcb-4a84-a83d-e9caaea44015.png)

In dark mode, nothing :
![image](https://user-images.githubusercontent.com/3462260/215114453-b7f7a2da-6f81-4b66-8ba3-1663b10b16bc.png)

**Comment by de-jcup** [comment] 2023-01-30 08:37
I think this is a duplicate of #467

**Comment by RoiSoleil** [comment] 2023-01-30 12:36
Yes it's duplicate

**Comment by RoiSoleil** [comment] 2023-01-30 12:36
Duplicate

**Closed as completed** 2023-01-30 12:36 UTC
