### ISSUE TITLE
"Failed to retrieve Windows Defender status." at startup of Eclipse 2024R06

### ISSUE THREAD

**Issue by pueblofunky** [eclipse-platform/eclipse.platform.ui#2192] opened 2024-08-14 18:42 UTC
After unzip eclipse-java-2024-06-R-win32-x86_64.zip into C:\Data\Programs\eclipse on
```
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎02.‎12.‎2021
OS build	19045.4651
Experience	Windows Feature Experience Pack 1000.19060.1000.0
```
and started Eclipse the workspace update started and then got 
```
Failed to retrieve Microsoft Defender status.
Failed to retrieve Microsoft Defender status.
Process terminated with unexpected result:
```

From "C:\Data\Dev\eclipse-ws\.metadata\.log"

```
!SESSION 2024-08-14 20:19:12.194 -----------------------------------------------
eclipse.buildId=4.32.0.20240606-1231
java.version=21.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

...

!ENTRY org.eclipse.ui.workbench 4 0 2024-08-14 20:19:43.049
!MESSAGE Failed to retrieve Microsoft Defender status.
!STACK 1
org.eclipse.core.runtime.CoreException: Failed to retrieve Microsoft Defender status.
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:323)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.runExclusionCheck(WindowsDefenderConfigurator.java:159)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.lambda$0(WindowsDefenderConfigurator.java:106)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Process terminated with unexpected result:

	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:320)
	... 4 more
!SUBENTRY 1 org.eclipse.ui.workbench 4 0 2024-08-14 20:19:43.049
!MESSAGE Failed to retrieve Microsoft Defender status.
!STACK 0
java.io.IOException: Process terminated with unexpected result:

	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:320)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.runExclusionCheck(WindowsDefenderConfigurator.java:159)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.lambda$0(WindowsDefenderConfigurator.java:106)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SESSION 2024-08-14 20:20:15.945 -----------------------------------------------
eclipse.buildId=4.32.0.20240606-1231
java.version=21.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product
```

Also get it during a start without existing workspace.
Haven't used 2024R03. Didn't happen with 2023R12.

I have no admin rights (on company computer). Bitdefender - as far as I can see - in Apps not installed but we use another one.

**Comment by jukzi** [comment] 2024-08-15 06:48
@HannesWell please take a look

**Comment by HannesWell** [comment] 2024-08-15 23:14
> I have no admin rights (on company computer). Bitdefender - as far as I can see - in Apps not installed but we use another one.

Based on your stack-trace I believe you are not allowed to launch Windows Powershell, are you?
If that's the case, this is probably a duplicate of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1884.
I forgot about that in the meantime, but try to fix it as soon as possible.
In the meantime you can use the workarounds presented there, i.e. disable this check for all Eclipse installations on your computer in the `Startup` preference page.



> java.io.IOException: Process terminated with unexpected result:
> 
> 	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:320)

On the other hand, if you reach this point, it actually means a `powershell` could be launched but the result is unexpected.

If you can launch a powershell, can you please run the command `(Get-MpComputerStatus).AMRunningMode` and let us know the exact result? And ideally the default local of your computer.

**Comment by pueblofunky** [comment] 2024-08-16 07:03
Hi @HannesWell,

I can run "Windows PowerShell" of course, but not "Windows PowerShell (Admin)" with my normal user.

When I run the command:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\xxx> (Get-MpComputerStatus).AMRunningMode
PS C:\Users\xxx> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  4648
```

there is no output!

I have another user-id with local admin rights and called PowerShell (Admin) and tried the command. The output is nothing - as for the normal user.

I've tried it on my private computer (my user has admin rights, default Windows 10 installation) and the output is "Normal" (also when I start PowerShell normal)). Same PowerShell version except at home revision is 4780. Interesting.

In Eclipse -> Preferences -> General -> Startup I run "Run exclusion check now" and get 

![image](https://github.com/user-attachments/assets/c260c2db-ab49-44a0-b3ac-0a9c1116ab44)

When I activate "Skip exclusion check on startup" and restart Eclipse 2024R06 I don't get the error anymore.

Of course the error happens the first time when you install Eclipse and this should be avoided in the future.

Thanks a lot. I will work with this setting in the meantime.

**Comment by HannesWell** [comment] 2024-08-17 19:34
> When I run the command:
> there is no output!

Alright. Thanks for checking this and all your other checks.

I created https://github.com/eclipse-platform/eclipse.platform.ui/pull/2204 to treat the empty string as status as the Windows Defender being inactive. This should solve this problem for you.

**Closed as completed** 2024-08-18 19:23 UTC
Labels: bug

**Comment by HannesWell** [comment] 2024-08-19 05:35
@pueblofunky can you please try out the latest I-build at https://download.eclipse.org/eclipse/downloads/drops4/I20240818-1800/ and verify that this problem is fixed for you?

**Comment by pueblofunky** [comment] 2024-08-19 06:56
> @pueblofunky can you please try out the latest I-build at https://download.eclipse.org/eclipse/downloads/drops4/I20240818-1800/ and verify that this problem is fixed for you?

I've tried to update my unzipped version of 2024R06 (as described https://download.eclipse.org/eclipse/updates/4.33-I-builds/I20240818-1800/) and did the manual check and also unselected the "skip" and restarted and in both cases the error occurred again.

I did a file scan with *1800* to check if the update did run correctly and found these:

```
C:\Data\Programs\eclipse2024R06\features\org.eclipse.help_2.3.1900.v20240818-1800
C:\Data\Programs\eclipse2024R06\features\org.eclipse.jdt_3.19.600.v20240818-1800
C:\Data\Programs\eclipse2024R06\plugins\org.eclipse.platform_4.33.0.v20240818-1800
C:\Data\Programs\eclipse2024R06\plugins\org.eclipse.help.base_4.4.500.v20240818-1800.jar
C:\Data\Programs\eclipse2024R06\plugins\org.eclipse.jdt_3.19.600.v20240818-1800.jar
C:\Data\Programs\eclipse2024R06\plugins\org.eclipse.rcp_4.33.0.v20240818-1800.jar
```

I hope this is ok so far. Sorry, but this was my first "special update" and I'm not sure if correct.

In case if it is wrong, is this fix included into "2024-09-M2-win32-x86_64.zip"? So then I could try this from scratch.

**Comment by merks** [comment] 2024-08-19 07:03
Did you try unzipping this to be sure you are trying the version that for sure has the fix?

https://download.eclipse.org/eclipse/downloads/drops4/I20240818-1800/download.php?dropFile=eclipse-SDK-I20240818-1800-win32-x86_64.zip

**Comment by pueblofunky** [comment] 2024-08-20 05:44
> Did you try unzipping this to be sure you are trying the version that for sure has the fix?
> 
> https://download.eclipse.org/eclipse/downloads/drops4/I20240818-1800/download.php?dropFile=eclipse-SDK-I20240818-1800-win32-x86_64.zip

I've also tried this 2 times but when I start the EXE nothing happens. Eclipse doesn't start nor raises an error. Not as normal user nor as with my admin user. Before the unzip I deleted the %USERPROFILE%\.eclipse, etc. and also the previous version. Also no new config directory created or any other file changes in the unzipped program folder. Sorry.
