### ISSUE TITLE
[Find/Replace] Pre-selected search string is always escaped even if RegEx search is disabled

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.ui#2270] opened 2024-09-14 13:56 UTC
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

If one opens the Find/Replace overlay with text in an editor being selected as initial search input, that search input is now always escaped even if RegEx search is disabled (see screenshot below).
This has the consequence that the non-RegEx search does not find the selected text because it treats the escape characters literally.

![grafik](https://github.com/user-attachments/assets/15ff1750-5d1c-44d4-bdb5-221bcf900e65)

Furthermore the search input is partally hidden/truncated at left, as displayed in the screenshot.

@Wittmaxi or @HeikoKlare could you please have a look at this?
IIRC this was introduced round about in the past week.

## Tested under this environment:
* OS & version: `Windows 10`
* Eclipse IDE/Platform version (as shown in *Help > About*): `Version: 2024-12 (4.34), Build id: I20240913-1800`

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment] 2024-09-14 16:08
Thank you for reporting, Hannes! This is a regression introduced by the recent refactoring for checking the availability and activation state of search options (in #2209). It will be fixed along with an according regression test via #2271.

**Comment by HannesWell** [comment] 2024-09-15 07:10
> Thank you for reporting, Hannes! This is a regression introduced by the recent refactoring for checking the availability and activation state of search options (in #2209). It will be fixed along with an according regression test via #2271.

Thank you!

Btw. do you have an idea why the text is only partially visible initially as shown in the screenshot?
Functionally it is irrelevant, but it does not look so nice and I wonder if this is a general problem in SWT?

**Comment by HeikoKlare** [comment] 2024-09-16 06:34
> Btw. do you have an idea why the text is only partially visible initially as shown in the screenshot?
> Functionally it is irrelevant, but it does not look so nice and I wonder if this is a general problem in SWT?

Sorry, I missed that statement in your original report. I have an idea and will try to evaluate it as soon as possible. In any case, I expect the problem to be solvable (easily).

I reopen the issue to be closed again via a PR for that additional issue.

**Comment by HeikoKlare** [comment] 2024-09-18 14:49
Intermediate update: I found the reason, I have fix, but not a proper one.

Reason for the behavior is that when the pre-selected text is set in the search input text field, it is not yet sized correctly. In the moment the text is set, it looks like this:
![image](https://github.com/user-attachments/assets/9c7e330b-1cc7-41c1-b02a-3d08f511bc2c)

Even if I enforce every layouting to be performed before setting the text, the wrong size is considered. I would expect a size recalculation to be sufficient, but at this point in time it should already have happened. What solves the problem is to set the text after the next paint event (by adding an execute-once paint listener at the end of the opening action). But that's rather an "I am not sure what to wait for, so wait for something that is definitely sufficient" solution than one that addresses the essential problem. I will try to find a better one...

**Comment by deepika-u** [comment] 2024-09-19 05:26
An observation: 
Issue of partial text visible is only seen when i select a text and open the FindReplaceOverlay freshly.
Issue of partial text **is not visible** when FindReplaceOverlay is already open and i select a different text for search.

**Comment by HeikoKlare** [comment] 2024-10-11 15:08
The replacement of the dialog-based with an integrated-composite based realization of the overlay (#2254) has fixed the second reported issue, i.e., the unnecessary "truncation" of the text. When updating to the next I-Build, the issue will be resolved:
This screencast shows the behavior of the old and new implementation:
![findreplace_truncation](https://github.com/user-attachments/assets/f55b2d0a-b45b-46cf-b1cc-a805572b7c9c)
Looking sharply, you can also see the deferred relayouting hapenning with the old implementation (which caused the truncation) while the new one immediately has the proper layout.

Thus closing this issue as resolved.

**Closed as completed by HeikoKlare** 2024-10-11 15:08 UTC
Labels: bug

**Comment by deepika-u** [comment] 2024-10-14 11:44
Not seeing truncation anymore even on a fresh FindReplaceOverlay. 

Verified on below build:
Eclipse SDK
Version: 2024-12 (4.34)
Build id: I20241013-1800
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 21.0.1+12-LTS
Java version: 21.0.1
