### ISSUE TITLE
UI freeze when searching over large files. Search View Filter viewer limit is not applied for children in TreeViewer.

### ISSUE THREAD

**Issue by raghucssit** [eclipse-platform/eclipse.platform.ui#2279] opened 2024-09-16 13:17 UTC
This issue is already reported here. Please close this one on Bugzilla as duplicate.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=575271

UI freezes over around 12 seconds if have a large search result in the second level tree onwards. The reason is Search View Filter viewer limit is not applied for children.
Use below snippet to generate 100k files with searchable text in it. Initiate File Search with text `text here`
  ```
      public static void main(String[] args) throws IOException {
                Path folder = Paths.get("...");
                if (!Files.deleteIfExists(folder)) {
                	Files.createDirectory(folder);
                }
                int n = 100_000;
                String baseContent = "text here";
                for (int i = 0; i < n; ++i) {
                        System.out.println("Writing file " + i);
                        StringBuilder content = new StringBuilder();
                        int k = 1;
                        if (i == 1001) {
                        	k = 1000;
                        }
                        for (int j = 0; j < k; ++j) {
                        	content.append(baseContent);
                        	content.append(" n");
                        	content.append(i);
                        	content.append(System.lineSeparator());
                        }
                        String fileName = "file" + i + ".txt";
                        Path file = folder.resolve(fileName);
                        try {
                                Files.write(file, content.toString().getBytes());
                        } catch (IOException e) {
                                System.err.println("Failed to write file: " + fileName);
                                e.printStackTrace();
                        }
                }
        }
```

**Comment by jukzi** [comment] 2024-09-16 14:52
Can you please provide screenshot how you search and what the result looks like? Is this a linux issue only?

**Comment by raghucssit** [comment] 2024-09-17 06:12
This is on linux. I did not test on windows.
UI will not show not responding but nothing can be performed on UI for 12 seconds and more.

100k files in PE. PE don't freeze because there is global viewer limit.
![100k-pe](https://github.com/user-attachments/assets/aa8500c6-839f-4dce-8467-6f9d7ae53296)


Search results view tries to expand the `dir` node to select first match.
![100k-sv](https://github.com/user-attachments/assets/68052726-87c0-4fd9-8abb-0211667a17a9)

**Comment by iloveeclipse** [comment] 2024-09-24 08:43
After playing a bit more with search view after merged changes I saw two things: 

1) We still have a full hang (forever on the example with 100.000 files here) after doing "F5" (run the current search again) - this is because the view update code calls `AbstractTextSearchResult.getMatchCount()` on every element to update and that traverses every match...
2) The tree mode in the search view doesn't show that the matches were filtered from the view, but table mode does it. This is more relevant now, because we filter more aggressive (not only the first level) and user might wonder "where are all the 1.000.000 matches gone".

I will push a PR addressing both issues in a moment.

**Comment by iloveeclipse** [comment] 2024-09-24 09:32
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/2320

**Comment by BeckerWdf** [comment] 2024-09-24 09:34
Once we have fixe this. Is this something we should also put into the New & Noteworthy document?
It's not a new feature but improving performance / reducing UI freezes is always "noteworthy" from my point of view. ;-)

**Comment by jukzi** [comment] 2024-09-24 09:56
we had performance improvements in every version. But at the same time we have so many regressions that it feels odd to praise xyz got faster while people complain uvw became worse.

**Comment by iloveeclipse** [comment] 2024-10-08 16:19
All planned fixes merged, closing.

**Closed as completed by iloveeclipse** 2024-10-08 16:19 UTC
Labels: bug, performance
