### ISSUE TITLE
Random failure of AbstractTreeViewerTest.testContains

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#1443] opened 2023-12-21 14:02 UTC
Failed on build of #1404 

```java
element must be available on the viewer
java.lang.AssertionError: element must be available on the viewer
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.jface.tests.viewers.AbstractTreeViewerTest.testContains(AbstractTreeViewerTest.java:342)
...
```

**Comment by HeikoKlare** [comment] 2023-12-21 14:05
Duplicate of: #1005

**Closed as completed by HeikoKlare** 2023-12-21 14:05 UTC
Labels: help wanted, test

**Comment by HeikoKlare** [comment] 2023-12-21 15:56
fwiw: failure was not in AbstractTreeViewerTest but in VirtualLazyTreeViewerTest
