### ISSUE TITLE
"Link with Editor" functionality not working with hierarchical project presentation

### ISSUE THREAD

**Issue by arjantijms** [eclipse-platform/eclipse.platform.ui#819] opened 2023-06-12 17:25 UTC
When I click in an open Java editor then the project explorer does not jump to the current class.

Setup in Project explorer:
- Two working sets, each with one project.
- Project presentation=hierarchical
- Projects closed with "Collapse all"
- "Link with Editor" is activated

Tested on many versions of Eclipse. Latest tested Version: 2023-03 (4.27.0)

**Comment by arjantijms** [comment] 2023-06-12 17:25
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=530257

**Comment by mickaelistria** [comment] 2023-06-12 18:59
Recent similar report #814 . Can you please check if you can reproduce it with a vanilla Eclipse SDK? Can you please give details about your environment, installed plugins and so on?

**Comment by Dinesh0723** [comment] 2024-02-05 11:10
The issue is not yet reproducible in eclipse 4.28 version.

**Comment by akurtakov** [comment] 2024-02-05 11:26
Closing as per previous comment.

**Closed as completed by akurtakov** 2024-02-05 11:26 UTC

**Comment by jstricker** [comment] 2024-02-23 15:46
@mickaelistria @Dinesh0723 @akurtakov This is reproducible with a basic installation of Eclipse IDE for Java Developers 4.28.0 on Mac using the following steps:

1. In Project Explorer, ensure "Link with Editor" is enabled.
2. In Project Explorer, double click to open a project.
3. Use the open resource dialog (shift+⌘+r) to open `src/main/java/com/example/package1/File1.java`
4. Use the open resource dialog to open `src/main/java/com/example/package2/File2.java`
5. Use the open resource dialog to switch back to `File1.java`, and note the link with editor functionality isn't working.
6. Use previous (fn+control+up arrow) and next (fn+control+down arrow) tab shortcuts to switch between open files, and note the link with editor functionality isn't working.
7. Click on the open tabs one at a time, and note the link with editor functionality isn't working.
8. In Project Explorer, manually expand the tree until you can see the contents of `package1` (but not `package2`).
9. Repeat steps 5-7, and note that the "Link with Editor" is working when the tab for `File1.java` is active (but not `File2.java`).
10. In Project Explorer, manually expand the tree until you can see the contents of `package2`.
11. Repeat steps 5-7, and note that the "Link with Editor" is working with `File1.java` and `File2.java`.

I've never looked at any of the Eclipse source, but perhaps whatever data that is used to enable the "Link with Editor" functionality is loaded only when the file itself or containing directory is opened via the Project Explorer.

**Comment by enexusde** [comment] 2024-10-06 08:19
The issue is reproducable in 4.32.0.

**Comment by mickaelistria** [comment] 2024-10-08 19:05
@jstricker @enexusde as this issue is closed so it is likely to get forgotten, please open a new ticket copying the details to reproduce with 4.32 you shared there.
