### ISSUE TITLE
[Viewers] JFace VirtualLazyTreeViewerTest tests failures on windows in the I-Build

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#369] opened 2022-09-30 06:08 UTC
The below tests in org.eclipse.jface.tests.viewers.VirtualLazyTreeViewerTest
 - testInsertSibling
 - testInsertSiblingReveal
 - testInsertSiblings
 - testInsertSiblingSelectExpanded
 
failed in trhe I-Build [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.jface.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) on windows, with the below error :

```
new siblings are visible

junit.framework.AssertionFailedError: new siblings are visible
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertNotNull(Assert.java:256)
at junit.framework.TestCase.assertNotNull(TestCase.java:399) 
```

**Comment by iloveeclipse** [comment] 2022-09-30 06:11
Duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/396

**Closed as completed by iloveeclipse** 2022-09-30 06:11 UTC
Labels: duplicate
