### ISSUE TITLE
Too much spacing in tree Widget for Eclipse 2024-03

### ISSUE THREAD

**Issue by kaspernielsen** [eclipse-platform/eclipse.platform.ui#1755] opened 2024-03-14 12:24 UTC
<img width="229" alt="Eclipse2024-03" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/75078/008e0490-a004-485f-b611-7ad4d045a818">
<img width="258" alt="Eclipse2023-12" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/75078/4615e1c4-4a8d-4992-b87f-a036a32967f4">

The default view of tree items has changed significantly in Eclipse 2024-03 compared to all previous versions. This results in ~ 20% less screen estate when using the widget

**Comment by akurtakov** [comment] 2024-03-14 13:29
Duplicate of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1674 it looks.

**Closed as completed by akurtakov** 2024-03-14 13:29 UTC
Labels: bug, macOS
