### ISSUE TITLE
Search overlay together with split editor: one pane or search overlay steals focus from the other pane

### ISSUE THREAD

**Issue by Ferdinand-Heinrich** [eclipse-platform/eclipse.platform.ui#2394] opened 2024-10-13 08:03 UTC
- [x] I verified I can reproduce this issue against a latest Eclipse IDE installation using the Eclipse Installer by Oomph with CDT (non-embedded) selected

## Steps to reproduce

From a fresh installation and clean workspace:

* create new C++ Hello World sample project

I tried

* Toggle Split Editor (Vertical) [Toggle Split Editor (Horizontal)]
* Ctrl+F to spawn search overlay
* Type something in the search overlay
* Click into the right [bottom] editor pane

I expected: the right [bottom] editor pane to receive the focus permanently

But got:
* on Windows 10: focus being in the right [bottom] editor pane for a split second, then jumping back to the left [upper] pane
* on Qubes OS 4.2 + Fedora 39: focus being in the right [bottom] editor pane for a split second, then jumping into the search overlay instead

## Here is some relevant log output

From `<workspace>/.metadata/.log`

* nothing logged

## Tested under this environment:
* OS & version:
  * Microsoft Windows 10 Pro, 10.0.19045 Build 19045
  * Qubes OS 4.2 + Fedora 39
* Eclipse IDE/Platform version (as shown in *Help > About*): 2024-09 (4.33.0)

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment] 2024-10-14 09:55
Thank you for reporting this issue!
I can confirm the issue for all kinds of text editors in the 4.33 release, so it also affects, e.g., the Java IDE. I have revalidated the issue with the most recent I-Build (in particular one including the change #2254) and was not able to reproduce the issue there.

Here is a recording with the old and new implementation showing the fixed behavior:
![findreplace_focus_split_view](https://github.com/user-attachments/assets/3f052ecf-0072-4680-9072-3e949c8d4662)

I will thus close this issue as fixed. In case the issue persists even after the mentioned change, please reopen it.

**Closed as completed by HeikoKlare** 2024-10-14 09:55 UTC
Labels: bug
