### ISSUE TITLE
New light theme causes UI inconsistencies in Tabbed Properties View

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.ui#2173] opened 2024-08-08 09:44 UTC
Recent changes to the light theme in the latest I-builds have set the background color for controls to a light grey (#f8f8f8). This [comment ](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114#issue-2418424128) suggests this is intended to create an overall darker background for a View. That's all very well if the View contains only one control, such as a Tree (Package Explorer), but if you have a View that contains many different controls you get an inconsistency in the controls' background colors. This is apparent in a [Tabbed Properties View](https://www.eclipse.org/articles/Article-Tabbed-Properties/tabbed_properties_view.html).

A Tabbed Properties View relies on [FormToolkit](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.forms/src/org/eclipse/ui/forms/widgets/FormToolkit.java) to create the controls. With the previous light theme the background color for most controls was white. With the latest changes some controls background colors are grey and some are white. This leads to an inconsistency in the UI and suggests that some controls are disabled. For example, a `Text` control is white (correct) but a `StyledText` control is grey and looks like it is disabled. Same for `Button` with style `SWT.TOGGLE | SWT.FLAT`.

The changes to the light theme have implemented the rule that most SWT controls that are in a View have their background color set to "#f8f8f8". This is not always desired.

**Comment by Phillipus** [comment] 2024-08-08 10:23
A `Table` in a View is the same grey color whether enabled or disabled so it's difficult to distinguish its enabled state (especially if the Table is empty). This is the case in any View, not just a Tabbed Properties View.

So a general point here is users will now not easily be able to distinguish enabled/disabled controls in Views.

**Comment by iloveeclipse** [comment] 2024-08-08 12:17
@Phillipus : could yuo please update description with screenshots before/after?

@mvm-sap, @BeckerWdf: could you please check? Probably related to https://github.com/eclipse-platform/eclipse.platform.ui/pull/2153 changes.

**Comment by Phillipus** [comment] 2024-08-08 13:23
Here's some before and after screenshots (taken on Windows 11)


### Text, StyledText and Button

1. The following screenshot is a Tabbed Property View containing a single-line `Text`, a multi-line `StyledText` control and a `Button` (with style `SWT.TOGGLE | SWT.FLAT`) _before_ the recent theme change. Backgrounds of all controls are white, controls are "enabled". The `Text` control is included for reference.

![before-text-controls](https://github.com/user-attachments/assets/d0ff80b6-201b-48b0-93d0-686db9c40b55)

2. The following screenshot is the same thing _after_ the change (controls are still "enabled"). The `Text` control background is still white but the backgrounds for `StyledText` and the `Button` are grey. The user might wonder whether these last two controls are enabled or disabled.

![after-text-controls](https://github.com/user-attachments/assets/a99dcb8b-b16c-4084-8bcc-44e7cb7ae1b9)

3. Here's the same thing after the change but this time the `StyledText` and `Button`are "disabled" They look the same as "enabled" (although the Button's image is a tad lighter).

![after-text-controls-disabled](https://github.com/user-attachments/assets/b6c9b15c-6f71-4ed0-9778-33aaee23dd9c)

### Table

1. The following screenshot is a `Table` _before_ the recent theme change (the Table is "enabled"). The background is white.

![before-table](https://github.com/user-attachments/assets/96d19a20-906e-4c06-b0b4-63a55a7007f8)

2. The following screenshot is the `Table` after the change. It's grey. The Table is still "enabled".

![after-table](https://github.com/user-attachments/assets/0729df98-5ff6-491f-b1e9-c356b26c2a7d)

3. Here's the same `Table` but "disabled". It looks the same as the enabled one.

![after-table-disabled](https://github.com/user-attachments/assets/0ecb44df-05d9-4d7e-b016-52b6dcef32de)

**Comment by Phillipus** [comment] 2024-08-08 13:35
And I've just noticed something else. Before this change to the light theme the tabbed property list selected item ("Main", "Properties", etc in the screenshots) was white and so you could see it was selected. After the theme change it is grey so harder to distinguish which tab is selected.

**Comment by Phillipus** [comment] 2024-08-08 13:37
And see also https://github.com/eclipse-platform/eclipse.platform.ui/issues/2171

**Comment by speckyspooky** [comment] 2024-08-09 20:26
Yes, I can confirm this behavior with the new modern style.
The same topic can be produced at our BIRT project with the eclipse designer.

_Table cell focused, register enabled, but not focused - register color "white"_
![grafik](https://github.com/user-attachments/assets/4f5fd349-7849-407d-83b5-825673e696e6)


_Table cell focused, register enabled, focus is set to id textbox - register color "gray"_
![grafik](https://github.com/user-attachments/assets/ee5f247e-9437-42e4-a004-62a3c0cd500a)

**Comment by speckyspooky** [comment] 2024-08-09 20:32
The same issue is given on text labe elements and radio buttons. In situations where the refresh wasnÄt done completely and the element doesnt have the focus the background of the elements is "gray" and the register is "white".

![grafik](https://github.com/user-attachments/assets/7d868e13-af8b-4d28-b733-a7e082acc1f8)

![grafik](https://github.com/user-attachments/assets/53cac04a-3ec3-40ee-9e67-a41b74ac9a69)

**Comment by Phillipus** [comment] 2024-08-10 08:30
@speckyspooky I'm not sure what you are showing in your screenshots. Judging by the shading on the tab items it doesn't look like you are using the Light theme in the latest Eclipse 4.33 I-builds. What is your target Eclipse theme version in these screenshots?

**Comment by speckyspooky** [comment] 2024-08-10 09:06
My target is only to confirm the issue with the color switch of white and gray color due to the new theme styling.

And second information this behavior seems also to be on other control elements. The blue borders shows the gray background the rest is white but sometimes all is gray or all is white. So it seems a mixture of enabled & un-/focused register and un-/focused elements.

Details of my eclipse version

- eclipse: 2024-09
- Version: 2024-09 (4.33)
- Build id: I20240807-0710

**Comment by Phillipus** [comment] 2024-08-10 09:19
@speckyspooky If that is a Tabbed Properties View with sections extending `AbstractPropertySection` then all controls should be created using `TabbedPropertySheetWidgetFactory` or `FormToolkit`. Some of those controls look like they might have been created not using those. And I don't understand how you have gradients on the tab items when the new theme makes those flat.

**Comment by speckyspooky** [comment] 2024-08-10 09:41
I can only say that since the new theme style is active there are some flickering available which get inconsitencies on the eclipse UI.
I agree that it can be caused at the situation that the elements wasn't created based on your mentioned classes but the UI elements are created before my time. I can see that some dialogs are using "FormToolkit".
At the end I'm confused if you say the elements must be created depended on your mentioned classes that I can see this kind of flickering between "white" and "gray" on registers and labels.
Then I would expect to have all with the old style or mixed white & gray but without switching of the colors.

**Comment by Phillipus** [comment] 2024-08-10 09:53
With the latest Light theme tab items will look flat like this:

![tabs](https://github.com/user-attachments/assets/4ae7c58b-e006-499a-8369-ff3e2ea3f5c2)

Yours look like this:

![theirs](https://github.com/user-attachments/assets/9e91ce58-1d20-4e10-aa47-b675a3e841c4)

**Comment by speckyspooky** [comment] 2024-08-10 10:00
Yes, the tabs are different. The problems seems to be familiar because its also a property tab. Of course not derived from your mentioned classes but the new themes have impact there.

But no problem, you can ignore my screens and be concentrated on your property tab.

**Comment by speckyspooky** [comment] 2024-08-10 13:28
Based on your mentioned classes I started a reserach and figured out that the main widget class is an extended class of the "FormToolkit":

![grafik](https://github.com/user-attachments/assets/e22a4525-1931-4bdd-aab0-5e8a62b6c0be)

**Comment by Phillipus** [comment] 2024-08-10 13:56
@speckyspooky OK, but I think this thread is getting a bit side-tracked now. The point is about grey controls and how they might be confused with disabled controls.

**Comment by speckyspooky** [comment] 2024-08-10 14:15
Of course if you talk about "enabled" and "disabled" layout situation then you are right my case is different.
The effect in my case is caused through the "unfocus" and "focus" of elements.

**Comment by mvm-sap** [comment] 2024-08-12 12:44
> @Phillipus : could yuo please update description with screenshots before/after?
> 
> @mvm-sap, @BeckerWdf: could you please check? Probably related to #2153 changes.

Yes, this change has caused the issue. I'm working on this by reverting changes. Will create a PR soon and update here

**Comment by mvm-sap** [comment] 2024-08-12 13:49
@Phillipus  I have created the PR as mentioned in the above comment. #2181
Please check and revert if you still figure out issues.

**Comment by BeckerWdf** [comment] 2024-08-15 11:37
This is fixed with: https://github.com/eclipse-platform/eclipse.platform.ui/pull/2181

**Closed as completed by BeckerWdf** 2024-08-15 11:37 UTC
Labels: bug, regression
