### ISSUE TITLE
Create New Source Folder dialog is behind all other windows and inaccessible

### ISSUE THREAD

**Issue by yannickbsaq** [eclipse-platform/eclipse.platform.ui#752] opened 2023-05-10 16:22 UTC
Hello,

Eclipse:
Version: 2023-03 (4.27.0)
Build id: 20230309-1520

I am trying to manually create a new source folder for my java project but the dialog window seems to be behind its parent window and the textbox cannot be written into.

<img width="688" alt="1" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/89541153/7f1ed7f1-ea7b-4403-bb77-ba862a14a5ed">

Then,
<img width="334" alt="2" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/89541153/1e5fdb30-cf83-4a4e-a881-f9ae80360e01">

Lastly,
<img width="426" alt="3" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/89541153/5cd03de7-a341-4d7f-9cae-3209dbc09dd2">

This window in the last image is behind the other 2 windows and the folder name field cannot be written into, it even stays open if I close the first 2 windows.

.project file if that helps:
```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>DistillateurJPA</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.buildship.core.gradleprojectbuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.buildship.core.gradleprojectnature</nature>
	</natures>
</projectDescription>
```

**Comment by iloveeclipse** [comment] 2023-05-11 07:24
This is a duplicate of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/557 and is fixed in master / will be in 4.28.

**Closed as completed by iloveeclipse** 2023-05-11 07:24 UTC
