### ISSUE TITLE
2023-06: F4 shortcut does not work anymore (open type hierarchy)

### ISSUE THREAD

**Issue by reto-hoehener** [eclipse-platform/eclipse.platform.ui#972] opened 2023-07-26 14:08 UTC
Works again if the F4 key binding from the command in the "Language Server" category is removed (maybe a conflict or precedence issue):

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/13407181/43de36cb-589a-4289-9d59-82be6c4d0327)

**Comment by iloveeclipse** [comment] 2023-07-26 14:21
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/644

**Closed as completed by iloveeclipse** 2023-07-26 14:21 UTC
