### ISSUE TITLE
Random failure of TableViewerTest.testContains

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#1444] opened 2023-12-21 14:02 UTC
Failed on a build of #1404 

```java
element must be available on the viewer
java.lang.AssertionError: element must be available on the viewer
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.jface.tests.viewers.TableViewerTest.testContains(TableViewerTest.java:203)
...
```

**Comment by HeikoKlare** [comment] 2023-12-21 15:52
Duplicate of #1183.

**Closed as completed by HeikoKlare** 2023-12-21 15:52 UTC
Labels: help wanted, test

**Comment by HeikoKlare** [comment] 2023-12-21 15:55
fwiw: failing test is not in TableViewerTest but in VirtualTableViewerTest
