### ISSUE TITLE
IAE: Comparison method violates its general contract in org.eclipse.jface.viewers.TreePathViewerSorter

### ISSUE THREAD

**Issue by kwin** [eclipse-platform/eclipse.platform.ui#1421] opened 2023-12-14 19:19 UTC
I get the following error when opening a nested project in the Project Explorer

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1234)
	at org.eclipse.jface.viewers.TreePathViewerSorter.sort(TreePathViewerSorter.java:105)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:670)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:849)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:615)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:802)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1593)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:913)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.treeExpanded(AbstractTreeViewer.java:1605)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:136)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.TreeItem.sendExpand(TreeItem.java:1031)
	at org.eclipse.swt.widgets.Tree.expandItem_expandChildren(Tree.java:1326)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6777)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1147)
	at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2191)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1139)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2642)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2158)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6320)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2264)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2511)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6444)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5692)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5831)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3986)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

The following bugzilla entries look related:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=371586
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=537394

## Tested under this environment:
* OS & version: Mac OS 14.2 (Sonoma)
* Eclipse IDE/Platform version (as shown in *Help > About*): 2023-09, Build id: 20230907-1323

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by kwin** [comment] 2023-12-14 19:39
It seems that the [Comparator contract](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Comparator.html#compare(T,T)) is violated by https://github.com/eclipse-platform/eclipse.platform.ui/blob/33d3e0380c449a6620e9d4909eb206021a59751b/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/ViewerComparator.java#L128. Not sure which aspect of the following, though:

> The implementor must ensure that [signum](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Integer.html#signum(int))(compare(x, y)) == -signum(compare(y, x)) for all x and y. (This implies that compare(x, y) must throw an exception if and only if compare(y, x) throws an exception.)

> The implementor must also ensure that the relation is transitive: ((compare(x, y)>0) && (compare(y, z)>0)) implies compare(x, z)>0.

> Finally, the implementor must ensure that compare(x, y)==0 implies that signum(compare(x, z))==signum(compare(y, z)) for all z.

This contract is checked by [Arrays.sort](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Arrays.html#sort(T%5B%5D,java.util.Comparator)) being called in https://github.com/eclipse-platform/eclipse.platform.ui/blob/33d3e0380c449a6620e9d4909eb206021a59751b/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/TreePathViewerSorter.java#L105.

**Comment by merks** [comment] 2023-12-14 19:44
Can you share something that reproduces the problem?  Otherwise folks would likely need to spend more time creating a test case than fixing the problem.

**Comment by kwin** [comment] 2023-12-14 19:47
I cannot even reproduce it reliably myself. Therefore I don’t know the circumstances (individual values) where the comparator is violating its contract

**Comment by laeubi** [comment] 2023-12-15 05:32
> Not sure which aspect of the following

It usually is some asymmetry in the compare function (that is delegated to getComparator here), or the underlying data is not constant and changes while comparing. If you see it regularly but not always you can put a break point and see what kind of data is compared and what comparator is used, then find a way to store that data and e.g. use [something like this](https://stackoverflow.com/a/35000727) to analyze it what can take a lot of time though and only explains what contract is violated but not why.

**Comment by jukzi** [comment] 2024-06-25 14:57
Closing due to missing reproducer

**Closed as not planned by jukzi** 2024-06-25 14:57 UTC
Labels: bug, needinfo
