### ISSUE TITLE
Build Platform UI / build (pull_request) github validation broken

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#228] opened 2022-07-23 10:17 UTC
@laeubi : probably some of recent dependencies changes broke guthub build validation, see for example 

https://github.com/eclipse-platform/eclipse.platform.ui/runs/7480162638?check_suite_focus=true for https://github.com/eclipse-platform/eclipse.platform.ui/pull/220

with tons of (unrelated to PR) errors like
```
Some blocking (most likely link/compilation) errors are present:
* Marker [on: /org.eclipse.ui.workbench/Eclipse UI/org/eclipse/e4/ui/workbench/addons/perspectiveswitcher/PerspectiveSwitcher.java, id: 1120, type: org.eclipse.jdt.core.problem, attributes: [arguments: 1:org.eclipse.swt, categoryId: 30, charEnd: 3160, charStart: 3145, id: 268435846, lineNumber: 68, message: The import org.eclipse.swt cannot be resolved, severity: 2, sourceId: JDT], created: 7/23/22, 9:52 AM]
```

**Comment by laeubi** [comment] 2022-07-23 10:27
I don't think that these errors are the cause of the failure, when downloading the build-logs the build is failed with:

> Failed to execute goal org.eclipse.tycho.extras:tycho-eclipserun-plugin:3.0.0-SNAPSHOT:eclipse-run (api-analysis) on project org.eclipse.ui.workbench: Error while executing platform: Error while executing platform: return code=10, see content of /home/runner/work/eclipse.platform.ui/eclipse.platform.ui/apiAnalyzer-workspace/data/.metadata/.logfor more details. -> [Help 1]

So something seems wrecked with API tools that then leads to the massive log outputs.

**Comment by laeubi** [comment] 2022-07-23 10:29
I have triggered https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-227/4/ to see if this also happens on the CI...

**Comment by akurtakov** [comment] 2022-08-28 05:02
Verification job has been working without issues for quite some time. Closing.

**Closed as completed by akurtakov** 2022-08-28 05:02 UTC
