### ISSUE TITLE
Problems View: Last entry rendered italics

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1526] opened 2024-01-19 14:09 UTC
happens only when maximal number of elements !=0
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/a23aa989-015f-4195-b9d2-2c3871c38233)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/03740490-e541-4292-92b0-f1eaa0c0b4bb)

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/de7c1227-9e1f-4df9-8726-c84d08336f76)
@raghucssit

**Comment by iloveeclipse** [comment] 2024-01-19 14:43
@jukzi : which project is it, I can't see this? I can't also observe that on any project I've checked in my workspace.

**Comment by jukzi** [comment] 2024-01-19 14:46
its in platform workspace. I think it was  where i had set filter to "box"
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/3fe11140-bda4-45fc-bfd7-836394013a1b)

**Comment by iloveeclipse** [comment] 2024-01-19 14:52
I can't get this state with only 7 warnings, every workspace is different.
Any way to have a reproducible example?

**Comment by jukzi** [comment] 2024-01-19 15:00
it was in the state after disabling some autobox warnings https://github.com/eclipse-platform/eclipse.platform.ui/pull/1527
currently i am in another state and don't see the problem anymore

**Comment by jukzi** [comment] 2024-01-19 15:02
ill try to keep n eye on it and inform you if i found exact reproducer

**Comment by raghucssit** [comment] 2024-01-19 15:03
7th element becoming italic only the case limit=6. And for any reason the node was not properly disposed and italic styling was left behind.
@jukzi Did you change the limit to 6 before ?

**Comment by jukzi** [comment] 2024-01-19 15:03
no, i think it was on 10000

**Comment by jukzi** [comment] 2024-01-19 15:04
maybe there where that many warnings but most of them had been filtered out?

**Comment by jukzi** [comment] 2024-01-19 15:33
got it again: current master on all repos. filter to "esource"
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/7ac86b31-b590-4a26-89c0-3e2fb7b6a9d2)
limit=1000

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/5e682fb8-c9d1-41e8-b963-76e611d48506)

**Comment by jukzi** [comment] 2024-01-19 15:35
ExpandableNodeCount 9 seems unreasonable high - i don't see anything is getting to the limit
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/44608cac-d68e-4026-9f75-0e07789b966d)

**Comment by iloveeclipse** [comment] 2024-01-19 15:37
It is in entire IDE, not only in the view. Close it and check numbers again.

**Comment by jukzi** [comment] 2024-01-19 15:38
after IDE restart the node count is 0 and i don't see the problem anymore.

**Comment by jukzi** [comment] 2024-01-19 15:41
when i then remove the filter=> nodecount=1, when i add the filter again => nodecount=0 but Problem reappeared
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/d5a27554-8ed2-4c1f-a8b1-50ed951ac2a6)

**Comment by iloveeclipse** [comment] 2024-01-19 15:46
OK, without filter one of the subtrees size must be over 1000 limit and node is shown, right? Once filter is set, node is not shown anymore, but the last element in same subtree is rendered as it would show the node (in italics)?

**Comment by jukzi** [comment] 2024-01-19 15:47
exactly

**Comment by iloveeclipse** [comment] 2024-01-19 15:47
How is the Problems view configured, which grouping / sorting ?

**Comment by iloveeclipse** [comment] 2024-01-19 16:13
I believe I've managed to reproduce it. What I did is to set the viewer limit to 10, in Problems view **disabled** grouping (Group By -> None) to have basically a flat table and set filters to show problems per selected project.

Now switching between project A that has ~100 problems and shows "expandable" node to a project B that has < 50 problems, Problems view renders the last element in the tree in italics.

So the best effects I see in JDT UI projects, switching between `org.eclipse.jdt.ui` and `org.eclipse.jdt.ui.unittest.junit` with 800 & 2 problems one can see the last (second) element in `org.eclipse.jdt.ui.unittest.junit` becoming italic, and switching back the second element in `org.eclipse.jdt.ui` becoming italic too (plus the last one which is "real" expandable node).

The problem with Problems view is the way how elements there are created. 
They are reused, and the styles are inherited if reused.

The styles are set in `org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerCell)`, so commenting the line 144 will the problem (but "expandable" node will not be rendered anymore differently). That could probably be fixed in using some different way to change the font used for it, but I remember it wasn't trivial at all to apply any special rendering.

**Comment by jukzi** [comment] 2024-01-19 16:13
I did not change sort or grouping

Jörg Kubitz

**Comment by iloveeclipse** [comment] 2024-01-19 16:20
> I did not change sort or grouping

Doesn't matter now, since I can reproduce without "extra" filters etc, see above.

We will follow up next week.

@raghucssit : we should think how we can change the rendering in a way it doesn't leave traces on reused elements.

**Comment by raghucssit** [comment] 2024-01-19 16:33
> I believe I've managed to reproduce it. What I did is to set the viewer limit to 10, in Problems view **disabled** grouping (Group By -> None) to have basically a flat table and set filters to show problems per selected project.
> 
> Now switching between project A that has ~100 problems and shows "expandable" node to a project B that has < 50 problems, Problems view renders the last element in the tree in italics.
> 
> So the best effects I see in JDT UI projects, switching between `org.eclipse.jdt.ui` and `org.eclipse.jdt.ui.unittest.junit` with 800 & 2 problems one can see the last (second) element in `org.eclipse.jdt.ui.unittest.junit` becoming italic, and switching back the second element in `org.eclipse.jdt.ui` becoming italic too (plus the last one which is "real" expandable node).
> 
> The problem with Problems view is the way how elements there are created. They are reused, and the styles are inherited if reused.
> 
> The styles are set in `org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerCell)`, so commenting the line 144 will the problem (but "expandable" node will not be rendered anymore differently). That could probably be fixed in using some different way to change the font used for it, but I remember it wasn't trivial at all to apply any special rendering.

I can also reproduce this way in problems view.
Initilally No Grouping
Filter = Errors/Warnings on selected resource and children
Set limit=10
Project A with 18 erros + 1 warning.
Probject B - No error/warnings.
Select Project A = 19 items created Flat structure.
Select Project B - Nothing shown.
Select A project again. 19 items created Flat structure
Enable Group By -> Type
Now 2nd group Title is italic.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10301131/8fd13b24-085b-440a-93c1-d4bc196ba7c7)

**Comment by raghucssit** [comment] 2024-01-19 16:35
> > I did not change sort or grouping
> 
> Doesn't matter now, since I can reproduce without "extra" filters etc, see above.
> 
> We will follow up next week.
> 
> @raghucssit : we should think how we can change the rendering in a way it doesn't leave traces on reused elements.

Yes. I will check.

**Comment by iloveeclipse** [comment] 2024-01-21 15:37
> Yes. I will check.

See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1531

**Closed as completed** 2024-01-21 18:28 UTC
Labels: bug, regression
