### ISSUE TITLE
Eclipse is not fully switching to "Dark Theme/Mode"

### ISSUE THREAD

**Issue by jrodriguez-rc** [eclipse-platform/eclipse.platform.ui#2536] opened 2024-11-25 11:27 UTC
Let's make sure issue is not already fixed in latest builds first.

- [X] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* Setting [SapMachine](https://sap.github.io/SapMachine/) Java

I tried

* Clean environment (fresh Windows install)
* Change Java version
* Switching Windows theme
* Switching Eclipse theme
* Updating graphic drivers

I expected: *All environment uses dark theme colors*

But got: *Menus still using light theme colors*
![image](https://github.com/user-attachments/assets/d6af0a14-a8d5-46c9-a6ed-68b20688d5b0)

## Tested under this environment:
* OS & version: Windows 11 (26100.2033)
* Eclipse IDE/Platform version (as shown in *Help > About*): 2024-09 (4.33.0)

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment] 2024-11-25 12:39
This issue came up with the 24H2 update of Windows 11 and is a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1546, which has already been fixed for the 2024-12 release. Please reopen if you experience the same issue with the 2024-12 release of Eclipse.

**Closed as completed by HeikoKlare** 2024-11-25 12:39 UTC
Labels: bug
