### ISSUE TITLE
Errors and warnings in javadoc during verification build

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.ui#1109] opened 2023-09-13 12:12 UTC
When building https://github.com/eclipse-platform/eclipse.platform.ui/pull/1108 the following errors and warnings are reported:
```
11:24:15.294 [ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1 - /home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/AbstractControlFactory.java:55: error: bad HTML entity
	 * The mnemonic indicator (character '&') is not displayed in a tool tip. To
	                                      ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/AbstractControlFactory.java:56: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                     ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/AbstractControlFactory.java:56: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                                                        ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/internal/ExpandableNode.java:95: warning: {@return} not at beginning of description
	 * {@return current offset in the original list of elements}
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/internal/ExpandableNode.java:112: warning: {@return} not at beginning of description
	 * {@return all remaining elements from original array starting with the element
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TableColumnFactory.java:122: error: bad HTML entity
	 * The mnemonic indicator (character '&') is not displayed in a tool tip. To
	                                      ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TableColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                     ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TableColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                                                        ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TreeColumnFactory.java:122: error: bad HTML entity
	 * The mnemonic indicator (character '&') is not displayed in a tool tip. To
	                                      ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TreeColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                     ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1108/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TreeColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                                                        ^
9 errors
2 warnings
```

**Comment by marcushoepfner** [comment] 2023-09-19 05:54
similar to #1103  (?)

**Comment by akurtakov** [comment] 2023-09-19 05:59
These are not similar, what @merks posted here is actually & that is not escaped aka & amp;

**Comment by merks** [comment] 2023-09-19 06:07
I noticed very many such errors, ones that apparent to have been around for a very long time.  It seems only the verification build logs/reports these errors, which really do look like things that ought to be fixed because it's really annoying for the verification build to be a sea of errors which appear to be ignored in terms of the build success/failure making it hard to find the "real" errors if any...

**Comment by akurtakov** [comment] 2023-09-19 06:15
Where do you see it ? E.g. in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1099/checks?check_run_id=16887602248 I don't see them.

**Comment by merks** [comment] 2023-09-19 06:26
Good question.  There are so many builds and I don't recall which one had all those errors in the log. 

These do look wrong though:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/4c3ff431-3824-4d83-8114-1bf0d3c56a6d)

So something should be reporting them, or if not, something reported them when I copied the errors from "the log".

**Comment by akurtakov** [comment] 2023-09-19 06:48
Javadoc is still in terrible state and was even worse and I've spent days improving it bit by bit which is extremely tedious process. It got to a state where "certain" things are clean and new issues fail the build so I would like first to get to a point where verifications are stable so people don't have an excuse to ignore them.

**Comment by laeubi** [comment] 2023-09-19 06:53
> making it hard to find the "real" errors if any...

Why are Javadoc errors not "real"? ... the inital purpose of this is/was to make people aware of Javadoc errors that otherwise only reported on the next i-build (if one looks there at the logs).

**Nerveless no one really needs to scan the logs**, we have scanners for this for example here (the linked PR is already merged so build logs are gone):

https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/23/

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/5454b994-16f5-4a4b-a772-15db22bae18c)

Also if you look at the summary here you get some parsed problems, I did this mostly for API Tools Errors/Warnings:

https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/6171755924

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/c09a8aa5-2713-4608-a501-aa908a8afa7e)

Also the Github Action Checks give a comprehensive summary for the cautious reviewer:
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/83517630-9c4f-420a-b40f-b33004fc779a)

**Comment by merks** [comment] 2023-09-19 07:03
@laeubi 

This is why I put "real" in quotes.   Obviously they are real yet this has been this way for a long time.  Clearly I did scan logs or I would not have been able to copy and paste the log content into this issue.  The question now is why did I find such errors in "the log" yet the current the logs says everything is fine and good.  

Moreover, is it a "real" problem to use & in Javadoc directly rather than using &amp; or is it not "real" a problem?  And, if not a "real" problem, why was the log I saw full of such errors?  If I'd known the problem of reported Javadoc errors wasn't generally reproducible, I would have take more care to keep track of where I found the errors...

**Comment by laeubi** [comment] 2023-09-19 07:12
> Moreover, is it a "real" problem to use & in Javadoc directly rather than using &

If you use the ampersand inside html tags, yes and that's what the tool complains about see:

https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html > Write Comments in HTML

>>  entities for the less than symbol (`<`) and the greater than symbol (`>`) should be written as `&lt;` and `&gt;`. Similarly, the ampersand (`&`) should be written as `&amp;`.

about reproducibility, as we have special builds that replace artifacts with baseline a tool like javadoc *might* decide to not run because everything seems up-to-date, but that's only a guess unless one can see a build log of "not reproducibility" (please note that this is [a special maven term](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) and eclipse builds are **in general not reproducible** anyways)

**Comment by laeubi** [comment] 2023-09-19 07:32
By the way I noticed some unnecessary maven warnings in the logs, should be fixed with:

- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1373

**Comment by laeubi** [comment] 2023-09-19 07:37
I created an issue at p2 as well about another source of many warnings that fill the log here:

- https://github.com/eclipse-equinox/p2/issues/322

**Comment by laeubi** [comment] 2023-09-19 07:44
If I [scan the consoleLog of the build](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/23/consoleText) I see this error:

```
16:12:14.912 [INFO] --- javadoc:3.0.1:jar (attach-javadocs) @ org.eclipse.jface ---
16:12:24.823 [ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1 - /home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/AbstractControlFactory.java:55: error: bad HTML entity
	 * The mnemonic indicator (character '&') is not displayed in a tool tip. To
	                                      ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/AbstractControlFactory.java:56: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                     ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/AbstractControlFactory.java:56: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                                                        ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/internal/ExpandableNode.java:95: warning: {@return} not at beginning of description
	 * {@return current offset in the original list of elements}
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/internal/ExpandableNode.java:112: warning: {@return} not at beginning of description
	 * {@return all remaining elements from original array starting with the element
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TableColumnFactory.java:122: error: bad HTML entity
	 * The mnemonic indicator (character '&') is not displayed in a tool tip. To
	                                      ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TableColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                     ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TableColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                                                        ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TreeColumnFactory.java:122: error: bad HTML entity
	 * The mnemonic indicator (character '&') is not displayed in a tool tip. To
	                                      ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TreeColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                     ^
/home/jenkins/agent/workspace/eclipse.platform.ui_master/bundles/org.eclipse.jface/src/org/eclipse/jface/widgets/TreeColumnFactory.java:123: error: bad HTML entity
	 * display a single '&' in the tool tip, the character '&' can be escaped by
	                                                        ^
9 errors
2 warnings
```

so it seems to be **well reproducible** but the Jenkins Javadoc scanner seems not to find it.
Instead it is classified as a Maven Problem:

https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/23/maven-warnings/moduleName.657231328/

by the way, currently the build is configured to **not** fails on javadoc problems ... so that why it show as `ERROR` in the log but not make the build itself fail...

**Comment by merks** [comment] 2023-09-19 07:55
Excellent detective work!

**Comment by laeubi** [comment] 2023-09-19 11:54
It seems even that this is specific to the HTML encoding problem where it is currently not handled so nice [in this PR](https://github.com/eclipse-platform/eclipse.platform/pull/697/files) I see javadoc annotations just as expected:

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/be1f7675-78c4-480f-b37b-f81377e95007)

(not that it seems people are bothering much more either if they are shown ;-)

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/dadf8943-1ad1-4306-b261-9504980c5530)

**Comment by HeikoKlare** [comment] 2024-01-18 14:08
The last remaining javadoc errors that can be found in build logs should be fixed with:
- #1516

@merks @laeubi Do you see anything left to do here or any reason to keep this issue open afterwards?

**Closed as completed** 2024-01-19 21:27 UTC
