### ISSUE TITLE
Marker id  not found not found when rerunning.

### ISSUE THREAD

**Issue by ewillink** [eclipse-platform/eclipse.platform.ui#681] opened 2023-04-01 14:12 UTC
When rerunning from the JUnit Test View a first run often fails with a "Launching Rerun'...' has encountered a problem. The 'DEtails' offer only Marker id nnn not found. Runnin g again works fine suggesing that the clean of of a spuriously stale marker could have occurred before the first rather than second run.

There is a corresponding error log without a stack trace.

eclipse.buildId=4.27.0.I20230302-0300
java.version=17.0.6
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -clean -data E:\Development\Chital\Workspace

This is a continuation of log file E:\Development\Chital\Workspace\.metadata\.bak_0.log
Created Time: 2023-04-01 11:58:58.070

Seems like the lack of a stack trace is also a bug since it gives us no real clue as to what the problem is.

**Comment by trancexpress** [comment] 2023-04-01 14:26
The exception stack trace should be added with: https://github.com/eclipse-platform/eclipse.platform/pull/384

I've reported this in platform since the logged error indicates core.resources: https://github.com/eclipse-platform/eclipse.platform.debug/issues/136

**Comment by merks** [comment] 2023-04-01 15:15
I've seen this problem last week as well...

**Comment by jukzi** [comment] 2023-05-17 06:35
Is this fixed and can be closed?

**Comment by iloveeclipse** [comment] 2023-05-17 06:39
> Is this fixed and can be closed?

Yes, this is a duplicate of closed https://github.com/eclipse-platform/eclipse.platform.debug/issues/136

**Closed as completed by iloveeclipse** 2023-05-17 06:39 UTC
